### ISSUE TITLE
Failed to import

### ISSUE THREAD

**Issue by athornfam2** [karthick-dkk/zabbix#4]
```Invalid tag "/zabbix_export/templates/template(1)/httptests/httptest(1)/steps/step(1)/required": a character string is expected.``` Server is 6.4

**Comment by karthick-dkk** [comment]
can you please share which step you got this error. please post a error snap for reference.

**Comment by EdneiRodrigues** [comment]
Hello. This error is caused by the line 292. The string 'required:' is empty.

**Comment by karthick-dkk** [comment]
Added the values:
required: "200"
